export const START_CLIENT_PROFILE_RETRIEVE = "START_CLIENT_PROFILE_RETRIEVE";
export const RETRIEVE_CLIENT_PROFILE_SUCCESS =
  "RETRIEVE_CLIENT_PROFILE_SUCCESS";
export const RETRIEVE_CLIENT_PROFILE_FAILED = "RETRIEVE_CLIENT_PROFILE_FAILED";
export const ADD_SELLABLE_TO_CATEGORY = "ADD_SELLABLE_TO_CATEGORY";
export const REMOVE_SELLABLE_FROM_PROFILE = "REMOVE_SELLABLE_FROM_PROFILE";
export const ADD_SELLABLE_CATEGORY_TO_PROFILE =
  "ADD_SELLABLE_CATEGORY_TO_PROFILE";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const SET_CATEGORY_NAME = "SET_CATEGORY_NAME";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const SET_TAB_INDEX_FOR_SELLABLE = "SET_TAB_INDEX_FOR_SELLABLE";
export const SET_IMAGE_TO_SELLABLE = "SET_IMAGE_TO_SELLABLE";
export const REMOVE_IMAGE_FROM_SELLABLE = "REMOVE_IMAGE_FROM_SELLABLE";
export const SET_SELLABLE_TEXT_PROP = "SET_SELLABLE_TEXT_PROP";
export const SET_SELLABLE_IMAGE_SIZE = "SET_SELLABLE_IMAGE_SIZE";
export const SWAP_SELLABLE_POSITIONS = "SWAP_SELLABLE_POSITIONS";
export const SET_SELLABLE_PRICE = "SET_SELLABLE_PRICE";
export const SET_SELLABLE_BONUS = "SET_SELLABLE_BONUS";
export const REMOVE_SELLABLE_BONUS = "REMOVE_SELLABLE_BONUS";
export const UPDATE_SELLABLE_BONUS = "UPDATE_SELLABLE_BONUS";
export const UPDATE_SELLABLE_PROMO = "UPDATE_SELLABLE_PROMO";
export const SET_VALIDATION_ERRORS = "SET_VALIDATION_ERRORS";

export const SET_ORDERS_FETCHING_STATUS = "SET_ORDERS_FETCHING_STATUS";
export const SET_CURRENT_ORDERS = "SET_CURRENT_ORDERS";
export const SET_ORDER_COMPLETED = "SET_ORDER_COMPLETED";

export const UPDATE_CONTACT_INFO = "UPDATE_CONTACT_INFO";
export const ADD_CONTACT_INFO_LIST_ELEMENT = "ADD_CONTACT_INFO_LIST_ELEMENT";
export const UPDATE_CONTACT_INFO_LIST_ELEMENT =
  "UPDATE_CONTACT_INFO_LIST_ELEMENT";
export const REMOVE_CONTACT_INFO_LIST_ELEMENT =
  "REMOVE_CONTACT_INFO_LIST_ELEMENT";
export const SET_MAP_IMAGE = "SET_MAP_IMAGE";
export const SET_MAP_LATLNG = "SET_MAP_LATLNG";
